Basic data flushing works

diff --git a/mkdata b/mkdata
--- a/mkdata
+++ b/mkdata
@@ -4,29 +4,23 @@ JAR="time"
 
 JAVANLP="$JAVANLP_HOME/projects/core/classes:$JAVANLP_HOME/projects/research/classes:$JAVANLP_HOME/projects/core/lib/xom-1.2.6.jar:etc/models.jar"
 CP="dist/$JAR.jar:etc/lib.jar:etc/scala-library.jar:etc/scala-compiler.jar:etc/jline.jar:etc/postgresql.jar:$JAVANLP:etc/jdom.jar:etc/joda-time.jar"
+	
+java -cp $CP -server -Xmx5000M -ea time.DataProcessor $@
 
-if [ "$1" == "tempeval2" ]; then
-	if [ "$2" == "" ]; then
-		echo "Usage: `basename $0` tempeval2 [annotate_directory] [language]"
-	elif [ "$3" == "" ]; then
-		echo "Usage: `basename $0` tempeval2 [annotate_directory] [language]"
-	else
-		java -cp $CP -server -Xmx1000M -ea time.TempEval2 $2 $3
-	fi
-#		cd aux/tempeval2 && ./toPsql.rb english data && cd ../.. &&\
-#			java -cp $CP -server -Xmx1000M -ea time.NumberAnnotator english
-elif [ "$1" == "timebank" ]; then
-	cd aux/timebank && ./toPsql.rb . data && cd ../.. &&\
-		java -cp $CP -server -Xmx1000M -ea time.NumberAnnotator timebank
-elif [ "$1" == "gutime" ]; then
-	if [ "$2" == "" ]; then
-		echo "Usage: `basename $0` gutime [annotate_directory]"
-		exit 1
-	fi
-	java -cp $CP -server -Xmx1000M -ea time.TimeAnnotator $2
-else
-	echo "Invalid dataset: $1"
-fi
+#if [ "$1" == "tempeval2" ]; then
+#	java -cp $CP -server -Xmx2000M -ea time.TempEval2 $@
+#elif [ "$1" == "timebank" ]; then
+#	cd aux/timebank && ./toPsql.rb . data && cd ../.. &&\
+#		java -cp $CP -server -Xmx2000M -ea time.NumberAnnotator timebank
+#elif [ "$1" == "gutime" ]; then
+#	if [ "$2" == "" ]; then
+#		echo "Usage: `basename $0` gutime [annotate_directory]"
+#		exit 1
+#	fi
+#	java -cp $CP -server -Xmx1000M -ea time.TimeAnnotator $2
+#else
+#	echo "Invalid dataset: $1"
+#fi
 
 
 
